### ISSUE TITLE
Socket leak (unix and http) with netcoreapp2.0 

### ISSUE THREAD

**Issue by bruegth** [dotnet/Docker.DotNet#275]
I got a socket leak with v3.125.0 with netcoreapp2.0 framework and docker 17.12 under Ubuntu 16.04.03.

I fixed this socket leak in my Fork (https://github.com/bruegth/Docker.DotNet) by removing the special HttpHandler with the default one from the framework.

**Comment by galvesribeiro** [comment]
Hello @bruegth 

Can you provide a repro case and/or a unit test that show the problem and what you did to fix it?

Thank you

**Comment by bruegth** [comment]
Currently not, sorry.
But I'm very similar with devlife in this issue https://github.com/Microsoft/Docker.DotNet/issues/206
(Cyclic calls of Inspect and List in 5 seconds intervall on serveral containers).

I think that https://github.com/Microsoft/Docker.DotNet/commit/6bac2f91e1a908047112d6cb288f0fc61283f833 won't fix it completly.

My first try was to switch from unix sockets to https sockets, but then I got also this leak. Then have replaces all the ManagedHandler stuff and take the default one from dotnetcore, now I got no leak anymore but with all the negatives (no unix or npipe, etc.).

**Comment by jterry75** [comment]
@bruegth - I am happy to review the code and port it where applicable. I don't exactly remember why we introduced `ManagedHandler` but I think at the time the `netstandardx.x` did not have it yet. A few questions:
1. Does this still support the multiplexed streams that we need for the stream style API's?
2. Does this compile only for `netstandard2.0` or does it work with all of our output targets?

Looks pretty cool!

**Comment by bruegth** [comment]
@jterry75 - I adapted it to my needs, so my fork is not usable for common use. 
> 1. Does this still support the multiplexed streams that we need for the stream style API's?

No, I currently don't need this.
> 2. I see that this broke our other output targets. Can we keep the other build targets too?

Yes, I only removed them to make it easier for me. With some more preprocessor directives it should work with the other targets too.

>Looks pretty cool!

Thanks

I hope my fork can deliver a few cherries.

**Comment by bruegth** [comment]
BTW - It is nice and simple to have unix / npipe streams, but my opinion is that in times of dotnetcore a developer who will use this package should make the connection to the container-daemon platform independent, so only https is usable for that.

**Comment by bruegth** [comment]
@HofmeisterAn Thx, it seems that your PR https://github.com/dotnet/Docker.DotNet/pull/586 fixes this old Bug too.
