### ISSUE TITLE
CreateImageAsync results in "no Host in request URL"

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/Docker.DotNet#332]
**Output of `dotnet --info`:**

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007517 [C:\Program Files\dotnet\sdk]
  2.1.200-preview-007576 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**What version of Docker.DotNet?:**

```
3.125.2
```

**Steps to reproduce the issue:**
I've pretty much copy/pasted the sample code from the main page with the exceptions of:
- `Parent` replaced with `Repo`
- Provided a 3rd parameter `IProgress<JSONMessage>`

```csharp
// Example: Create an image by pulling from Docker Registry
// The code below pulls fedora/memcached image to your Docker instance using your Docker Hub 
// account. You can anonymously download the image as well by passing null instead of AuthConfig 
// object:

Stream stream  = await client.Images.CreateImageAsync(new ImagesCreateParameters() {
	Repo = "fedora/memcached",
	Tag = "alpha",
}, null, new Progress());


  public class Progress : IProgress<JSONMessage>
        {
            public void Report(JSONMessage value)
            {
                Debug.WriteLine(value.ToString());
            }
        }
```

**What actually happened?:**
An exception was thrown with the following message:
```
Docker.DotNet.DockerApiException: 'Docker API responded with status code=InternalServerError, response={"message":"Get http:: http: no Host in request URL"}
```

**What did you expect to happen?:**
I expected the client to download the image from the public docker feed.

- Please explain why did I get that error message. Should I also specify `ImagesCreateParameters.FromSrc` ?
- What should the `ImagesCreateParameters.FromSrc` value be?

**Comment by mmisztal1980** [comment]
**Update**
I've decided to play around and made some progress:

```charp
 await _client.Images.CreateImageAsync(new ImagesCreateParameters()
            {
                FromImage = "alpine:latest",
                Repo = "alpine",
                Tag = "latest",
                FromSrc = "https://registry-1.docker.io"
            }
```
I've played around and got this to work, however:
- I've had to set **FromSrc** to `https://registry-1.docker.io`
- Settings **FromSrc** to `https://registry-1.docker/io/v2` results in a 401
- Not specifying **FromImage** results in **0B** being downloaded.

Can you cross-reference this with your front page?
- Shouldn't **FromSrc** default to `https://registry-1.docker.io` or something similar?
- Is **FromImage** required? 

Best regards
/Maciek

**Comment by Rachel-ResDiary** [comment]
The code above, i.e.:

```
    public class Foo
    {
        async void bar()
        {
            DockerClient client = new DockerClientConfiguration(new Uri("npipe://./pipe/docker_engine")).CreateClient();

            Stream stream = await client.Images.CreateImageAsync(new ImagesCreateParameters()
            {
                Repo = "fedora/memcached",
                Tag = "alpha",
            }, null, new Progress());
        }
    }

    public class Progress : IProgress<JSONMessage>
    {
        public void Report(JSONMessage value)
        {
            Debug.WriteLine(value.ToString());
        }
    }
```
Doesn't even compile for me. The error I get is "Cannot implicitly convert type void to System.IO.Stream"

I'm trying to consume this library from a .Net core Application. Is that simply not possible?

**Comment by jterry75** [comment]
@mmisztal1980 - Typically what I do in these cases is determine what part of the documentation was misleading by comparing the following:
- Run the docker daemon in -D (debug) mode
- Issue a call `docker pull` etc that does the command I am trying to do with `Docker.DotNet`
- Issue my same code in `Docker.DotNet` against this deamon compare the `json` that was sent in both cases. 

Sometimes the `Docker.DotNet` does not have defaults that the docker cli might because this is really a rest layer wrapper not a docker cli replacement. But if the defaults are different in a meaningful way I would welcome any PR's to help people out.

@Rachel-ResDiary - `Docker.DotNet` is absolutely supported in `.NET Core` that was a major goal. What version of `netstandard` are you using etc so I can help you understand what is wrong with the code.

**Comment by Rachel-ResDiary** [comment]
@jterry75 

Thanks for your response. This is what ended up working for me:

```
        static DockerClient localDockerDaemon = new DockerClientConfiguration(new Uri("npipe://./pipe/docker_engine")).CreateClient(); //Default implementation of 'IDockerClient'

        public void PullImage(string imageName, string tag, IProgress<JSONMessage> optionalProgressMonitor = null)
        {
            if (optionalProgressMonitor == null) optionalProgressMonitor = new DebugProgressHandler();
            Task getImageTask = localDockerDaemon.Images.CreateImageAsync(new ImagesCreateParameters()
            {
                FromImage = imageName,
                Tag = tag
            }, null, null, optionalProgressMonitor, new CancellationToken(false));
            getImageTask.Wait();
        }
```

**Comment by jterry75** [comment]
Oh I see. Your first example would of worked but you are trying to `await` a task that does not return a `Stream` hence the error.

```c#
await client.Images.CreateImageAsync(
    new ImagesCreateParameters
    {
        Repo = "fedora/memcached",
        Tag = "alpha",
    }, null, new Progress());
```

This is the same as saying what you did your second example of: 
```c#
var t = client.Images.CreateImageAsync(...)
t.Wait()
```
