### ISSUE TITLE
.NET Core 2.0 EOL. Move to 2.1

### ISSUE THREAD

**Issue by jterry75** [dotnet/Docker.DotNet#344]
.NET Core 2.0 has reached end of life. Update to 2.1

**Comment by galvesribeiro** [comment]
Yep, but do we need to change anything? I mean, we are targeting `netstandard2.0` and not `netcoreapp2.0`, right? `netstandard2.0` still the same...

**Comment by jterry75** [comment]
Likely not. Probably all we need to do is update the appveyor to use the -Channel LTS that I can see. But otherwise should be fine with everything else.

**Comment by HofmeisterAn** [comment]
@galvesribeiro We can close this too. Library targets `netstandard2.0` and `netstandard2.1`. Test are running `net6.0`.
