### ISSUE TITLE
npipe connection on Windows not working as expected

### ISSUE THREAD

**Issue by tfenster** [dotnet/Docker.DotNet#369]
**Output of `dotnet --info`:**

```
dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   2.2.101
 Commit:    236713b0b7

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**What version of Docker.DotNet?:**

```
3.125.2
```

**Steps to reproduce the issue:**
1. git clone https://github.com/tfenster/npipeproblem
2. cd npipeproblem
3. dotnet build
4. dotnet run

**What actually happened?:**
I create a container, depending on the parameters using either npipe or http (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L30-L31). Then I create and start a container (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L35-L59). I create a task to get the output from the container (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L61-L88) and then another one to run a couple of commands, depending on the parameters with a sleep of 5 seconds between them (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L90-L127). The commands are: Check the file system (`Get-ChildItem`),  create a folder (`mkdir temp`) and check the file system (`Get-ChildItem`) again. In the end I kill my main process (`Get-Process ping | Stop-Process`). Those commands are just for demonstration purposes, they don't really matter. In the end I remove the container again (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L132).

All of this works if I connect through http and also if I connect through npipe without delays between the commands (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L15-L22). However if I connect through npipe and run the commands with 5 second delays (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L24-L25), `WriteAsync` after the first delay never comes back (https://github.com/tfenster/npipeproblem/blob/master/Program.cs#L105).

Am I missing something or doing anything wrong?

**What did you expect to happen?:**
All commands should run fine, no matter if through npipe or http and with out without delays

**Additional information:**

**Comment by tfenster** [comment]
It turns out this is fixed in the current state of the Docker.DotNet source code. After running into a wall for quite some days, I decided to debug through the source code, cloned the repo and directly used it instead of the nuget package. And it just worked there...

@jterry75 maybe it is time for a release?

**Comment by glucaci** [comment]
I saw also that a lot was changed in the master.
A preview release will be very useful.
