### ISSUE TITLE
Issue with checking path variable

### ISSUE THREAD

**Issue by eapyl** [dotnet/Docker.DotNet#395]
looks like an issue with the code in `master` branch - [link](https://github.com/microsoft/Docker.DotNet/blob/4e1b2429f5d90c2a3b319bd568d14e7b9535d5a5/src/Docker.DotNet/DockerClient.cs#L387)
![image](https://user-images.githubusercontent.com/1629511/57912927-c9075900-788b-11e9-992c-f8bc3232252b.png)
I believe it should be 
```
if (string.IsNullOrEmpty(path))
{
    throw new ArgumentNullException(nameof(path));
}
```

**Comment by HofmeisterAn** [comment]
@galvesribeiro We can close this as well, it's fixed.
