### ISSUE TITLE
Can you provide a strong name for the Nuget package?

### ISSUE THREAD

**Issue by sczhh** [dotnet/Docker.DotNet#403]
Could not load file or assembly 'Docker.DotNet, Version=3.125.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

**Comment by steffen-wilke** [comment]
+1

**Comment by ScubaDrew** [comment]
Is there a solution to this? Thanks @sczhh

**Comment by jterry75** [comment]
@galvesribeiro is working on a release here now that we are part of the foundation. Thanks

**Comment by ftballguy45** [comment]
still nothing really?

**Comment by lukashankeln** [comment]
No news on this yet?

**Comment by MSraye** [comment]
When using the latest version of this nuget package, similar error was encountered. 

Checked it with dotPeek and found // Assembly Docker.DotNet, Version=3.125.0.0, Culture=neutral, PublicKeyToken=null. 

Are the bits really signed?

**Comment by HofmeisterAn** [comment]
PR got merged, but there is no new version (release). We need to wait for something > `3.125.0`.
