### ISSUE TITLE
Hostconfig missing properties to enable GPU usage

### ISSUE THREAD

**Issue by druanoor** [dotnet/Docker.DotNet#425]
Hi.

I need to create containers that use GPU. In order to do that, you need to configure the property "DeviceRequests" from HostConfig Object, but this library doesnt have it yet. (There are other properties that are "missing" too)

Hope it gets updated as soon as possible.

Thanks & Regards

**Comment by HofmeisterAn** [comment]
@galvesribeiro The property is now part of the `HostConfig` class. We can close this issue.
