### ISSUE TITLE
Update containers

### ISSUE THREAD

**Issue by cotin18** [dotnet/Docker.DotNet#435]
**Output of `dotnet --info`:**

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.101
 Commit:    bc5f8df0f5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04
 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.101/

Host (useful for support):
  Version: 3.0.1
  Commit:  19942e7199

.NET Core SDKs installed:
  3.0.101 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**What version of Docker.DotNet?:**

```
<PackageReference Include="Docker.DotNet" Version="3.125.2"/>
```

I cant seem to find to find a way to update a running container with this package

https://docs.docker.com/engine/reference/commandline/update/
https://docs.docker.com/engine/api/v1.40/#operation/ContainerUpdate

What I can find is a model named ContainerUpdateParameters. 
There might be a way to use this to update a container but I'm not sure how i would make that work. 

If not i would like to request this feature.

**Comment by moaead** [comment]
Pretty old post but the is to either build it or use the nuget mentioned in the read me 
https://ci.appveyor.com/nuget/docker-dotnet-hojfmn6hoed7

**Comment by cotin18** [comment]
Yeah i ended up building the latest.
