### ISSUE TITLE
[Announcement] Docker.DotNet -> .Net Foundation

### ISSUE THREAD

**Issue by galvesribeiro** [dotnet/Docker.DotNet#443]
Hello folks!

We are in process of move Docker.Dotnet to .Net Foundation and as many of you may have noticed,  the repo was already been moved to dotnet/ GitHub organization. 

Microsoft has donated the project to the Foundation as we requested!

What does that mean for us? Well, to start, we get:

1. We can have our own release cadence. While under Microsoft/ org, even as an OSS project, we had to follow their release cadence and we were struggling to get a release out since the packages weren't meeting internal requirements;
2. We now are free to explore new .Net Core/Standard APIs since we are not obligated to maintain back compat with old and unsupported .Net Framework releases.

So, I just would like to thanks @jterry75  and the other MSFT folks along to the contributors of the project up to Today! Many projects are using this library and we're looking forward to provide more capabilities to the package and enhance it even more!

**So, what now?**

As we are in process of migrate things over to the new project structure/governance under the foundation, we still need a few things to get set up before we can launch a new release like for example, CI/CD pipeline, package signing, and NuGet publish.

Once we have those last things settled, we're going to release a package version with the current codebase.

After this package is pushed out, we will start designing the new versions and the revamp of the codebase using modern things provided Today by .Net Core and .Net Standard libraries like `Span`/`Memory`, replace the current golang based code generator with one based on Roslyn, etc.

I can't wait to start on the new life of this package.

Again thank you all from the community and contributors, lets revamp this package again!

I'll keep you all posted.

Cheers!

**Comment by cfauchere** [comment]
This is good news. What does it mean for PRs? Should it be done against this repo? I have one out for a month or so.

**Comment by tfenster** [comment]
@galvesribeiro This looked promising for a while but now there is silence again for 3 months... Can we expect any progress anytime soon?

**Comment by jterry75** [comment]
@tfenster - The transfer was completed. Are you looking for something specific?

**Comment by galvesribeiro** [comment]
Hey folks, 

Sorry, I've been away to deal with some personal issues of this pandemic. 

I've got the artefacts required for the package signing from the .Net Foundation.

I'll will do my best to get it out until the weekend.

Will update the status here.

Thanks

**Comment by jterry75** [comment]
Thanks @galvesribeiro. Lets close this one out since it was transferred and then when you get the signing updated we can close out the others.

**Comment by tfenster** [comment]
@jterry75 primarily an updated release so that I no longer have to build it from source to use in my projects

**Comment by jterry75** [comment]
Ok great. That is what @galvesribeiro is working on to get the signing requirements using the foundations key. Thanks

**Comment by galvesribeiro** [comment]
Yo folks! Again, sorry for all the delay.

The sign configuration is implemented on this PR: https://github.com/dotnet/Docker.DotNet/pull/454

If anyone want to follow that up or review please feel free.

After that gets merged, we will move forward with the releases.

Again, thanks for wait, I appreciate that.
