### ISSUE TITLE
Pipeline poluted with "Docker.DotNet.Models.JSONMessage"

### ISSUE THREAD

**Issue by andreujuanc** [dotnet/Docker.DotNet#467]
![image](https://user-images.githubusercontent.com/360052/95089190-240d4a80-0724-11eb-8d28-5ecb07425725.png)

**What version of Docker.DotNet?:**

```
3.125.4
```

**Steps to reproduce the issue:**
1. Xunit fixture that uses this library
2. Run the pipeline

**What actually happened?:**
There are hundreds of logs with the same message: `Docker.DotNet.Models.JSONMessage`

**What did you expect to happen?:**
I did not expect these messages to be printed, nor I did logged anything out to the console. I do not know why those messages are there. But they are clearly not mine.

**Additional information:**
Tried to see if there was any log config in the library, but found nothing.

This is not critical, but it pollutes the logs, and when something goes wrong, it's hard to find.

EDIT: Improved text to clarify issue

**Comment by saoc90** [comment]
Hi @andreujuanc 

There is no explicit `.ToString()` on Docker.DotNet.Models.JSONMessage implemented. If you want to print out your message you have to implement something like this:

``` csharp
        private void PrintJsonMessage(JSONMessage message)
        {
            if (!string.IsNullOrEmpty(message.ErrorMessage))
            {
                Console.WriteLine($"Error: {message.ErrorMessage}");
            }
            else
            {
                Console.WriteLine(message.ProgressMessage);
            }
        }
```

**Comment by andreujuanc** [comment]
Hi @saoc90 , 
Maybe I didn't explained myself properly.
I do not want to print anything. I just use the library, and I'm getting those messages out of the blue 😐

**Comment by andreujuanc** [comment]
Updated the nuget version and now it does not print this message :S
Maybe it was something in Azure Devops? no idea. Anyway, closing. Thanks!
