### ISSUE TITLE
ListImagesAsync does not work properly with MatchName

### ISSUE THREAD

**Issue by IgorFedchenko** [dotnet/Docker.DotNet#489]
**Output of `dotnet --info`:**

```
Пакет SDK для .NET Core (отражающий любой global.json):
 Version:   3.1.102
 Commit:    573d158fea

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**What version of Docker.DotNet?:**

```
3.125.4
```

**Steps to reproduce the issue:**
1. Remove cached docker image from your local machine (in my case, let it be `mcr.microsoft.com/mssql/server:2017-latest` as an example)
2. Execute `client.Images.ListImagesAsync(new ImagesListParameters { MatchName = "mcr.microsoft.com/mssql/server:2017-latest" })` - this returns list of all existing images, 81 item in my case. But should return empty list.

**What actually happened?:**
Or CI system stopped working, due to the errors like this:
```
Docker.DotNet.DockerContainerNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: mcr.microsoft.com/mssql/server:2017-latest"}
```

After some debugging, we found that before creating docker container we are checking if container already exists in the system. To do that, we run `client.Images.ListImagesAsync` with image's name and tag, and checking if our image exists on the machine.
But now it does not work, because instead of empty list this method returns lots of images that do not match to specified `MatchName`.

**What did you expect to happen?:**
`client.Images.ListImagesAsync(new ImagesListParameters { MatchName = "mcr.microsoft.com/mssql/server:2017-latest" })` returns empty list if no such image installed on the machine.

**Comment by Arkatufus** [comment]
`MatchName` seemed to be broken, `Filters` works, but it is very verbose and annoying to write.

**Comment by dgvives** [comment]
I ran into the same problem months ago. Turns out `MatchName` parameter was removed from Docker API on v1.25, 

[ImageListParameters](https://github.com/dotnet/Docker.DotNet/blob/8e3cf4f7ac386e2f76791afc2c427a7b7884cd5e/src/Docker.DotNet/Models/ImagesListParameters.Generated.cs#L7#L14) has been updated to reflect this change, and yes, it is verbose. 

Just copy paste from somebody else

```csharp
var imageListResponse = await _dockerClient.Images.ListImagesAsync(
    new ImagesListParameters
    {
        Filters = new Dictionary<string, IDictionary<string, bool>>
        {
            ["reference"] = new Dictionary<string, bool>
            {
                ["ubuntu:latest"] = true
            }
        }
    },
    cts.Token
);
```

**Comment by padtm** [comment]
The `Dictionary` types can be inferred, so it need not be so verbose. 
```cs
var imageListResponse = await _dockerClient.Images.ListImagesAsync(
    new ImagesListParameters
    {
        Filters = { ["reference"] = { ["ubuntu:latest"] = true } }
    },
    cts.Token
);
```

**Comment by IgorFedchenko** [comment]
Well, I guess `MetchName` should be just removed from the `Docker.DotNet` API then.

**Comment by padtm** [comment]
It was [15 days ago on master](https://github.com/dotnet/Docker.DotNet/commit/8e3cf4f7ac386e2f76791afc2c427a7b7884cd5e#diff-2a33b59c2e875ff9b3ab5bed9ea00b82795d7401753aced8564304d64ab6a111L84-L86) but it's not yet released.

**Comment by IgorFedchenko** [comment]
Ah, all right then 👍

**Comment by dgvives** [comment]
@padtm nice suggestion

**Comment by andreujuanc** [comment]
Hi, 

I'm using the new filter expression and I get a null reference exception. 

v3.125.4
wsl2 linux 

ill do the filtering in memory for now.

**Comment by CumpsD** [comment]
Same here, the call itself throws a NRE

```csharp
            var images = await _client
                .Images
                .ListImagesAsync(
                    new ImagesListParameters
                    {
                        Filters =
                        {
                            ["reference"] =
                            {
                                [Configuration.Image.RegistryQualifiedName] = true,
                            },
                        },
                    })
                .ConfigureAwait(false);
```

**Comment by CumpsD** [comment]
Seems you had to create the Dictionary anyway:

```csharp
            var images = await _client
                .Images
                .ListImagesAsync(
                    new ImagesListParameters
                    {
                        Filters = new Dictionary<string, IDictionary<string, bool>>
                        {
                            ["reference"] =
                            {
                                [Configuration.Image.RegistryQualifiedName] = true,
                            },
                        },
                    })
                .ConfigureAwait(false);
```
