### ISSUE TITLE
Example of using 'Volumes' property of a 'CreateContainerParameters' class instance.

### ISSUE THREAD

**Issue by kooroshsajadi** [dotnet/Docker.DotNet#491]
It would be good to have an example of adding volumes with defining their names and paths using an instance of the CreateContainerParameters class as this is something I'm struggling with.

**Comment by paul-michalik** [comment]
Is this implemented at all? I am struggling with filling the `Models.EmptyStruct` properly...

**Comment by DustinReagan** [comment]
I'm having the same problem.  I can't figure out how to add Volume mappings using `EmptyStruct`.  An example using `CreateContainerParameters` & Volumes would be greatly appreciated.

**Comment by mcintyre321** [comment]
I think this might help https://github.com/dotnet/Docker.DotNet/issues/226#issuecomment-689708713
