### ISSUE TITLE
Docker client unable to find docker images

### ISSUE THREAD

**Issue by oliver-scott** [dotnet/Docker.DotNet#495]
Hello, just wondering if anyone has encountered a similar issue or is able to advise.

We have been using this library for about 6 months now:

`_dockerClient = new DockerClientConfiguration(new Uri(
                     RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
                         ? "npipe://./pipe/docker_engine"
                         : "unix:///var/run/docker.sock"
                 )).CreateClient();`

Just this week though we have started having issues on our build server, where the client seems unable to find any docker images:

`Docker.DotNet.DockerContainerNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: influxdb:1.8.3"}`

The docker image definitely exists. I have tried other images too and they all fail with the same error:

`Docker.DotNet.DockerContainerNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: bitnami/kafka:latest"}`

`Docker.DotNet.DockerContainerNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: hello-world:latest"}`

Our build agents are running Ubuntu. We don't get this error on our local Windows machines so it appears to be specific to Linux.

We are using 3.125.2 of Docker.DotNet, we have also tried 3.125.4 and get the same issue.

Has anyone seen this before, or aware of any changes that need to be made to the configuration of the docker client?

Thanks in advance for any help.

**Comment by dgvives** [comment]
It looks like it is not related to the library but to build agent. I had this sort of problems first time using Docker.DotNet within CI/CD agents, and it took me a while until managed to review docker api calls output.

Here an example I used today for another project 


```c#
public static class Program
    {
        public static async Task Main()
        {
            using var tester = new Tester();
            await tester.GetContainerLogs();
        }
    }

    public class Tester : IDisposable
    {
        private readonly CancellationTokenSource _cts;
        private readonly DockerClient _dockerClient;
        private readonly string _imageId;
        private readonly TestOutput _output = new TestOutput();

        public Tester()
        {
            using var configuration = new DockerClientConfiguration();
            _dockerClient = configuration.CreateClient();
            _cts = new CancellationTokenSource();
            _imageId = "hello-world";
        }

        public void Dispose()
        {
            _dockerClient.Dispose();
            _cts.Dispose();
        }

        public async Task GetContainerLogs()
        {
            using var containerLogsCts = new CancellationTokenSource(TimeSpan.FromSeconds(50));

            var tcs = new TaskCompletionSource<string>(containerLogsCts.Token);
            using (_ = containerLogsCts.Token.Register(() => tcs.SetCanceled()))
            {
                await _dockerClient.Images.CreateImageAsync(
                    new ImagesCreateParameters
                    {
                        FromImage = "hello-world:latest"
                    },
                    null,
                    new Progress<JSONMessage>((m) => Console.WriteLine(m)),
                    default);

                var createContainerResponse = await _dockerClient.Containers.CreateContainerAsync(
                    new CreateContainerParameters()
                    {
                        Image = _imageId,
                        Name = Guid.NewGuid().ToString(),
                        Tty = true
                    },
                    _cts.Token
                );

                await _dockerClient.Containers.StartContainerAsync(
                    createContainerResponse.ID,
                    new ContainerStartParameters(),
                    _cts.Token
                );

                await _dockerClient.Containers.StopContainerAsync(
                    createContainerResponse.ID,
                    new ContainerStopParameters(),
                    _cts.Token
                );

                var containerTask = _dockerClient.Containers.GetContainerLogsAsync(
                    id: createContainerResponse.ID,
                    new ContainerLogsParameters
                    {
                        ShowStderr = true,
                        ShowStdout = true,
                        Timestamps = true
                    },
                    containerLogsCts.Token,
                    new Progress<string>((m) => Console.WriteLine(m))
                );

                containerLogsCts.CancelAfter(TimeSpan.FromSeconds(1));

                await Assert.ThrowsAsync<TaskCanceledException>(() => containerTask);

                _output.WriteLine(JsonConvert.SerializeObject(new
                {
                    containerTask.AsyncState,
                    containerTask.Exception,
                    containerTask.IsCanceled,
                    containerTask.IsCompleted,
                    containerTask.IsCompletedSuccessfully,
                    containerTask.IsFaulted,
                    containerTask.Status
                }));
            }
        }
    }

```


`new Progress<JSONMessage>((m) => Console.WriteLine(m))` is key here to produce messages

**Comment by dgvives** [comment]
One note on previous post: to use a different docker image compatible with ubuntu version used on build agent should be enough

**Comment by oliver-scott** [comment]
Thanks for the reply. I've found and resolved the issue, the Ubuntu version turned out to be a red herring.

The issue was with this line:

`var images = await dockerClient.Images.ListImagesAsync(new ImagesListParameters { MatchName = name });`

We used this to check whether the image exists before creating it. However the MatchName argument doesn't seem to filter the images as expected - it returns all images. So if you were to pull the images, and then change it to pull a newer version of one of those images, that existence check would prevent the new image from being created and the container would fail to create, as that particular image wasn't on the machine. So for now we have removed this existence check, as the CreateImage method handles it anyway.

Thanks for your help - the Progress<string> logging pointed me in the right direction when I saw that it wasn't actually pulling the image before creating the container.

**Comment by dgvives** [comment]
We had the same problem months ago. 
In case you want to use ListImagesAsync and avoid pulling an existing image
```csharp
 var images = await _dockerClient.Images.ListImagesAsync(
    new ImagesListParameters
    {
        All = true,
        Filters = new Dictionary<string, IDictionary<string, bool>>
        { 
            ["reference"] = new Dictionary<string, bool> 
            { 
                ["ubuntu:latest""] = true
            } 
        }
    },
    token
);
```

**Comment by oliver-scott** [comment]
thanks for your help.
