### ISSUE TITLE
New release after one year?

### ISSUE THREAD

**Issue by bruegth** [dotnet/Docker.DotNet#526]
> I hope we can get on track to working on it and having faster shipping from now on.
> 
> _Originally posted by @galvesribeiro in https://github.com/dotnet/Docker.DotNet/issues/418#issuecomment-672861238_

**Comment by drleq** [comment]
I would also like to pick up a newer build to address a number of outstanding issues.  Critically, we're looking for the fix on CancellationTokens (see https://github.com/dotnet/Docker.DotNet/pull/487) which is causing deadlocks.

In the (hopefully) short term we will be forced to produce our own build as the AppVeyor only includes older builds.
