### ISSUE TITLE
The type of namespace HostConfig could not be found. 

### ISSUE THREAD

**Issue by maaz-bin-asad** [dotnet/Docker.DotNet#527]
`DockerClient client = new DockerClientConfiguration()
               .CreateClient();
            
            await client.Containers.StartContainerAsync(
            "39e3317fd258",
            new HostConfig
                {
                DNS = new[] { "8.8.8.8", "8.8.4.4" }
                });`

**Comment by HofmeisterAn** [comment]
The type `HostConfig` is part of the `CreateContainerParameters` type (in your case `client.Containers.CreateContainerAsync(...)`). Can we close this issue?
