### ISSUE TITLE
Wrong serializer for Timeout property in type HealthConfig

### ISSUE THREAD

**Issue by demdh** [dotnet/Docker.DotNet#533]
When providing an `TimeSpan` for the Timeout property, e.g. `TimeSpan.FromSeconds(5)`, of the type [`HealthConfig`](https://github.com/dotnet/Docker.DotNet/blob/f58748616cc5b679b25496926c5688294c94d850/src/Docker.DotNet/Models/HealthConfig.Generated.cs) you get the following exception:

```
Exception has occurred: CLR/Docker.DotNet.DockerApiException
An exception of type 'Docker.DotNet.DockerApiException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Docker API responded with status code=BadRequest, response={"message":"Timeout in Healthcheck cannot be less than 1ms"}'
```

It can be fixed by multiplying the second value with 1000000, e.g. `TimeSpan.FromSeconds(5 * 1000000)`.

It seems that the configured `JsonConverter` is wrong and should be `TimeSpanNanosecondsConverter` instead of `TimeSpanSecondsConverter`.

Docker.DotNet Version: 3.125.4

**Comment by HofmeisterAn** [comment]
@galvesribeiro We can close this issue, it's fixed: b9463efeb56c980fce4843d2909be497248b8e35.
