### ISSUE TITLE
How to check if the Docker desktop is running?

### ISSUE THREAD

**Issue by murtazabasu** [dotnet/Docker.DotNet#539]
I have a very simple question, I would like to know if the docker daemon is running if not I would like to wait for about a minute until the docker daemon is started. 

Currently I have a work around where I try to pull a image from the hub and if it return a System.TimeoutException I assume that the daemon is not running. 

Is there a more cleaner way of knowing if the docker desktop is running?

**Comment by mggrand** [comment]
Just check if the Process `docker` (Windows) or `dockerd` (Unix) is running like done in here https://github.com/dotnet/Docker.DotNet/blob/c71df18a0f76f30160f61f908353ad1e53677377/test/Docker.DotNet.Tests/ISystemOperations.Tests.cs#L40

**Comment by murtazabasu** [comment]
Thank you that worked.

So basically, the `var dockerProcess` gives a null if the docker daemon is not working.
