### ISSUE TITLE
ContainerLogsParameters is missing until parameter

### ISSUE THREAD

**Issue by 13750573877** [dotnet/Docker.DotNet#543]
Use GetContainerLogsAsync to obtain container logs. The until parameter is missing from the ContainerLogsParameters model parameters, so it is impossible to obtain container logs by page.

**https://docs.docker.com/engine/reference/commandline/logs/**
**https://docs.docker.com/engine/api/v1.41/#operation/ContainerLogs**

**Comment by HofmeisterAn** [comment]
@galvesribeiro we can close this issue. It's closed by #577, #584.
