### ISSUE TITLE
Run tests that are using docker.dotnet from a DockerFile - SocketException : Cannot assign requested address

### ISSUE THREAD

**Issue by Retrorado** [dotnet/Docker.DotNet#545]
**Output of `dotnet --info`:**

```
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Środowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**What version of Docker.DotNet?:**

```
3.125.5
```

**Steps to reproduce the issue:**
1.  Create Dockerfile for this solution (place it inside src/Docker.Dotnet project). Example:
```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
ENV TZ=Europe/Warsaw
WORKDIR /tmp

COPY . ./
RUN dotnet restore /tmp/Docker.DotNet.sln

WORKDIR /tmp/test/Docker.DotNet.Tests
RUN dotnet test --verbosity n Docker.DotNet.Tests.csproj

WORKDIR /tmp/src/Docker.DotNet
RUN dotnet publish Docker.DotNet.csproj -c Release -o /out -f=netstandard2.0

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
COPY --from=build /out ./
ENTRYPOINT ["dotnet", "Docker.DotNet.dll"]
```

2.  Run build command from main solution folder Docker.DotNet
`docker build -f src/Docker.DotNet/Dockerfile -t docker-dotnet:1 .`

3. Get the exception:
System.Net.Http.HttpRequestException : Connection failed
System.Net.Sockets.SocketException : Cannot assign requested address

**What actually happened?:**
I am using Docker.DotNet for tests in my project. Every time I run my tests, new container is created with a database for my tests.
Everything is fine when tests are running directly from computer or CI/CD pipeline using dotnet test (both on windows and linux). The problem occurs when I want to run the tests using docker build, then it crashes :)
From what I have determined the error occurs at the time of any operation using DockerClinet, for example:
` await _dockerClient.Containers.CreateContainerAsync`

**What did you expect to happen?:**
To be able to run a tests, that are using Docker.DotNet to create a container/image/volume, from a docker.

**Additional information:**
I suspect that this relates to the docker socket mapping, but this is only my guess.

I would appreciate any help.
Thanks!

**Comment by dgvives** [comment]
Hello, is it possible docker not being installed inside the image you are using for testing? 
That would be mcr.microsoft.com/dotnet/sdk:5.0

**Comment by Retrorado** [comment]
> 

This is what you mean? I have added install script for docker installation from https://get.docker.com. 
Unfortunately the same error still occurs :(

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
ENV TZ=Europe/Warsaw
WORKDIR /tmp

RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy curl && \
    apt-get install -qy curl && \
    curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh

COPY . ./
RUN dotnet restore /tmp/XInfo.sln

WORKDIR /tmp/tests/XInfo.API.IntegrationTests
RUN dotnet test --verbosity n XInfo.API.IntegrationTests.csproj

WORKDIR /tmp/src/XInfo.API
RUN dotnet publish XInfo.API.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
ENV LANG=pl_PL.UTF-8 \
    LANGUAGE=pl_PL \
    LC_ALL=pl_PL.UTF-8 \
    TZ=Europe/Warsaw \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
WORKDIR /app
COPY --from=build /out ./
ENTRYPOINT ["dotnet", "XInfo.API.dll"]
```

**Comment by dgvives** [comment]
Ok, have you tested if docker is running in the image before launching the tests?
In any case, this is not an issue with the library but with the use of it

**Comment by Retrorado** [comment]
Yes, you are right, docker is not running.
I've added this to dockerfile:
```
RUN sudo service docker start
RUN sudo docker info
```
and now I'm getting this error, on docker info command:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

And once again, you are right - it's an issue with the use of this library :)

**Comment by dgvives** [comment]
You could try adding some delay between service start and docker info. 
Since this is not an issue, please close it. You can add more comments to the issue after closing it and I'll have a look at it later in case you have any other question, just for the pleasure of providing help  👌

**Comment by Retrorado** [comment]
Thanks @dgvives, I really appreciate it.

Unfortunately, adding sleep command didn't help. I'm still getting the same error.

**Comment by dgvives** [comment]
Well, you may check if docker is installed and also if it is running before executing docker info

**Comment by Retrorado** [comment]
I'm not able to start docker.
I've also tried command `sudo dockerd`, but I'm getting error:
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables: Permission denied (you must be root).

Well, I read, that it's a good practice to run tests before building image. 
Right now I'm starting to read more about it and I'm not entirely sure if that's the case :)
