### ISSUE TITLE
How to setup --expose=[] and -p=[]  parameters

### ISSUE THREAD

**Issue by Alex-1357** [dotnet/Docker.DotNet#550]
Hello, docker documentation (https://docs.docker.com/engine/reference/run/#expose-incoming-ports) has two different parameters

      --expose=[] Expose a port or a range of ports inside the container
      -p=[] Publish a container's port or a range of ports to the host

How to setup this parameters? Unfortunately I see only one parameters related to port

![docker_01282022_000706-1](https://user-images.githubusercontent.com/86534217/151455671-b77d1f21-740a-446e-aedf-28ed449d41a6.png)

**Comment by OneCricketeer** [comment]
Related #134

**Comment by Alex-1357** [comment]
Yes, I found it. This is my solution.

![docker_01292022_000822-1](https://user-images.githubusercontent.com/86534217/151628666-6366e80e-c72d-484c-8504-61a297b7c5e8.png)

        Dim ExposedPorts = New Dictionary(Of String, EmptyStruct)
        Dim ContainerPort = "46003"
        ExposedPorts.Add(ContainerPort, New EmptyStruct)

        Dim OneHostBinding As New PortBinding With {.HostIP = "157.XX.XX.86", .HostPort = "46003"}
        Dim HostBindingList As New List(Of PortBinding)
        HostBindingList.Add(OneHostBinding)
        Dim PortBindings As New Dictionary(Of String, IList(Of PortBinding))
        PortBindings.Add("46003", HostBindingList)

        Dim Labels = New Dictionary(Of String, String)
        Labels.Add("TstKey", "TstVal")
        Dim CMD = New List(Of String)
        CMD.Add("pwd")
        Dim Prm = New CreateContainerParameters With {
                      .Image = "alexev275/digiwage:latest",
                      .Name = $"digiwage.{Guid.NewGuid}",
                      .Env = Env,
                      .ExposedPorts = ExposedPorts,
                      .Labels = Labels,
                      .Tty = True,
                      .HostConfig = New HostConfig With {.PortBindings = PortBindings}
        }

**Comment by HofmeisterAn** [comment]
Can we close this? Do you need any further help?
