### ISSUE TITLE
Misleading exception when attempting to connect to a network

### ISSUE THREAD

**Issue by cdavernas** [dotnet/Docker.DotNet#559]
**Output of `dotnet --info`:**

```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**What version of Docker.DotNet?:**

```
3.125.5
```

**Steps to reproduce the issue:**

Attempt to connect to a network, using a new `NetworkConnectParameters` without specifying the `Container` property

**What actually happened?:**

An ArgumentNullException is thrown, pointing at the `parameters` argument, which is not null

**What did you expect to happen?:**

An ArgumentNullException is thrown, pointing at the `parameters.Container` property, instead of `parameters`, which is misleading.

**Comment by HofmeisterAn** [comment]
Is this still an issue? Can we close it?
