### ISSUE TITLE
Multiple portbindings to 1 new container

### ISSUE THREAD

**Issue by tvdrpe** [dotnet/Docker.DotNet#569]
Hey guys,

I want to run a container with multiple portbindings, with the CLI it would be "-p 8120:80 -p 9120:443 ".
How do i translate this into code?

I have this in HostConfig = new HostConfig() {
![image](https://user-images.githubusercontent.com/66520609/177744215-3f7331cf-70a0-4364-b364-5da34c032499.png)

}

Portbindings only accepts 1 Dictionary ... how can I add a second one for "443"?

Thanks for you help!

**Comment by alexandreberton** [comment]
Yes it's one dictionary but a dictionary can have multiple items ;)

Create a dictionnary with all your entries and then set PortBindings.

For example I have this kind of code on my side to do the same job:

`
private Dictionary<string, IList<PortBinding>> GetPortBindings(List<PortCouple> portCouples)
        {
            var portBindings = new Dictionary<string, IList<PortBinding>>();

            foreach (var port in portCouples)
            {
                portBindings.Add(port.InternalPort, new List<PortBinding> { new PortBinding { HostIP = "0.0.0.0", HostPort = port.HostPort } });
            }

            return portBindings;
        }

public class PortCouple
    {
        public string HostPort { get; set; }
        public string InternalPort { get; set; }
        public PortCouple(string hostPort, string internalPort)
        {
            HostPort = hostPort;
            InternalPort = internalPort;
        }
    }
`

So on you sample you can do something like this:

`
var portBindings = new List<PortCouple>
{
      new PortCouple(8120, 80),
      new PortCouple(9120, 443)
};
`

then just set PortBinding property with this list.

**Comment by tvdrpe** [comment]
@alexandreberton Thank you very much, solved my issue!
