### ISSUE TITLE
is Docker.DotNet really a .NET foundation project?

### ISSUE THREAD

**Issue by mikeblas** [dotnet/Docker.DotNet#610]
**Output of `dotnet --info`:**

```
N/A
```

**What version of Docker.DotNet?:**

```
N/A
```

**Steps to reproduce the issue:**
1. Go to the project docs here: https://www.nuget.org/packages/Docker.DotNet/
2. Scroll down to the bottom. Click on the link to DotNet Fdountation. (goes to https://www.nuget.org/packages/Docker.DotNet/ )

**What actually happened?:**

It's 404.

Also, searching for Docker.DotNet at the foundation website doesn't yield any matching results.

**What did you expect to happen?:**

A working link.

**Additional information:**

Same problem in the GitHub readme.md file.

**Comment by HofmeisterAn** [comment]
Yes, they onboard it 2020: https://github.com/dotnet-foundation/projects/issues/52

**Comment by mikeblas** [comment]
Then, why isn't it listed in the .NET foundation directory?

**Comment by galvesribeiro** [comment]
Yes, it is a .Net foundation projection. You can check the foundation is on the owners list: 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/4714040/221209066-0e0e25fe-be33-4d80-a484-8ffae8a9d76a.png">

I think if there is a broken link on the foundation websites you can open an issue there or submit a PR to their documents to fix any broken link.

We still use all the foundation infrastructure and support just like any other project.

**Comment by galvesribeiro** [comment]
Jesus sorry, I thought it was their page had a broken link. Yeah, they've changed the website. I'm going to fix it.

**Comment by galvesribeiro** [comment]
Ok, now they are fixed on our side. Thanks for the report.

**Comment by mikeblas** [comment]
I can't find the owners list you're talking about.

The README fix isn't much of a fix as there's no way to verify the claim that this project is a member of the Foundation.

The README here seems to be fixed, but the README at NuGET: (https://www.nuget.org/packages/Docker.DotNet/) still has the 404 link.

**Comment by HofmeisterAn** [comment]
> I can't find the owners list you're talking about.

He's talking about the NuGet dependency owner. But I agree, I would expect that the project is visible in the new .NET Foundation site as well. You find in the the old version though: https://old.dotnetfoundation.org/projects.

> The README here seems to be fixed, but the README at NuGET: (https://www.nuget.org/packages/Docker.DotNet/) still has the 404 link.

This requires a new release.

**Comment by galvesribeiro** [comment]
> This requires a new release.

Nop it doesn't. I just updated it. Sorry, I forgot to get it there.

> But I agree, I would expect that the project is visible in the new .NET Foundation site as well. 

I'll ping the MSFT folks internally to see what do we need to do to update there.

Thanks for the report.

**Comment by HofmeisterAn** [comment]
> Nop it doesn't. I just updated it. Sorry, I forgot to get it there.

Right, it's not included in the NuGet. Then an update on NuGet.org works.

**Comment by galvesribeiro** [comment]
Yeah, that is intentional so we can update when necessary without a release.

**Comment by HofmeisterAn** [comment]
😉
