### ISSUE TITLE
InspectContainerAsync() -> Health is always null.

### ISSUE THREAD

**Issue by VictorioBerra** [dotnet/Docker.DotNet#623]
**Output of `dotnet --info`:**

```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.115 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22427.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**What version of Docker.DotNet?:**

```
3.125.13
```

**Steps to reproduce the issue:**

```csharp
await client.Images
	.CreateImageAsync(
		new ImagesCreateParameters()
		{
			FromImage = "mcr.microsoft.com/mssql/server",
			Tag = "latest",
		},
		new AuthConfig(),
		new Progress<JSONMessage>());

var sqlServerContainer = await client.Containers.CreateContainerAsync(new CreateContainerParameters()
{
	Image = "mcr.microsoft.com/mssql/server",
	Name = "linqpad-sql1",
	Hostname = "sql1",
	ExposedPorts = new Dictionary<string, EmptyStruct>
	{
		{ "1433", default }
	},
	HostConfig = new HostConfig
	{
		PortBindings = new Dictionary<string, IList<PortBinding>>
		{
			{
				"1433",
				new List<PortBinding>
				{
					new PortBinding
					{
						HostIP = "0.0.0.0",
						HostPort = "1433",
					},
				}
			},
		},
	},
	Env = new List<string>
	{
		"ACCEPT_EULA=Y",
		"MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>",
	},
	Healthcheck = new HealthConfig
	{
		Interval = TimeSpan.FromSeconds(10),
		Timeout = TimeSpan.FromSeconds(3),
		Retries = 3,
		StartPeriod = (long)TimeSpan.FromSeconds(60).TotalNanoseconds, // long??? What goes here?? Nanoseconds, Miliseconds, seconds?? No docs!
		Test = new List<string>
		{
			"/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '<YourStrong@Passw0rd>' -Q \"Select 1\"",
		}
	},
});

while(true)
{
	var i = await client.Containers.InspectContainerAsync(createSQLServerContainerResponse.ContainerID);
	i?.State.Health.Dump(); // <--------------------- Always null!!!!
	Thread.Sleep(5000);
}
```

**What actually happened?:**
InspectContainerAsync() -> State.Health is always null

**What did you expect to happen?:**
InspectContainerAsync() -> State.Health should no be null.

**Additional information:**
I cant find any docs that tell me what to put for StartPeriod which is a `long`.

**Comment by HofmeisterAn** [comment]
> long??? What goes here?? Nanoseconds, Miliseconds, seconds?? No docs!
> I cant find any docs that tell me what to put for StartPeriod which is a long.

It is documented in the Docker Engine API [docs](https://docs.docker.com/engine/api/v1.42/#tag/Container/operation/ContainerCreate), see the section **Create a container**, parameter **Healthcheck**.

> Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.

Furthermore, your `Test` property is wrong. See the docs too, it requires additional information about the command:

> - ["CMD", args...] exec arguments directly
> - ["CMD-SHELL", command] run command with system's default shell

It should be something like `Test = new List<string> { "CMD", "true" }`

**Comment by VictorioBerra** [comment]
@HofmeisterAn thank you,

Adding "CMD" to my test args now gets me health information:

```csharp
Healthcheck = new HealthConfig
  {
  Interval = TimeSpan.FromSeconds(10),
  Timeout = TimeSpan.FromSeconds(3),
  Retries = 10,
  StartPeriod = (long)TimeSpan.FromMinutes(1).TotalNanoseconds,
  Test = new List<string>
  {
	  "CMD",
	  $"/opt/mssql-tools/bin/sqlcmd",
	  "-S",
	  "localhost",
	  "-U",
	  "SA",
	  "-P",
	  sqlServerPassword,
	  "-Q",
	  "Select 1",
  }
},
```

![image](https://user-images.githubusercontent.com/2934507/227552818-46fdb296-9717-435d-b79f-d41683da08da.png)

Regarding my question about the docs, why is there no XML comments so that information can easily be seen in the IDE?

![image](https://user-images.githubusercontent.com/2934507/227553104-67d22d7a-28c6-4fb5-818d-95cbbfd1dfe2.png)

**Comment by VictorioBerra** [comment]
Also one last question, I could not find info in the docs on how the health check is actually evaluated.

If I set the health values to absurdly low values:

```csharp
Interval = TimeSpan.FromSeconds(1),
Timeout = TimeSpan.FromSeconds(3),
Retries = 2,
StartPeriod = (long)TimeSpan.FromSeconds(1).TotalNanoseconds,
```

I get the following:

![image](https://user-images.githubusercontent.com/2934507/227555264-6797b4e0-d702-43a3-8cd1-334f97cdb794.png)

Each blue box is the result of a `InspectContainerAsync` every 2 seconds.

You can see there is a list of health check results, the second one says that the health check exceeded timeout (3s), but status is still starting, and eventually it goes healthy.

I guess I expected the status to say "unhealthy" and to never go healthy again since it exceeded the timeouts and retries? My main question would be how could I use `InspectContainerAsync` to determine that the health check has failed completely and needs user intervention?

**Comment by HofmeisterAn** [comment]
> Regarding my question about the docs, why is there no XML comments so that information can easily be seen in the IDE?

I do not know why the author did not add more XML documentation, but I can imagine that copying the documentation would not add much value. Simply look at the official ones; they will always be up-to-date. This is in general a good advice working with Docker.DotNet.

> You can see there is a list of health check results, the second one says that the health check exceeded timeout (3s), but status is still starting, and eventually it goes healthy.

I think the health state is controled by `Retries`:

> The number of consecutive failures needed to consider a container as unhealthy.
