### ISSUE TITLE
What units are HealthConfig.StartPeriod in?

### ISSUE THREAD

**Issue by njlr** [dotnet/Docker.DotNet#659]
The minimum working value I could find is `1_000_000L`, which suggests nanoseconds. 

Is this correct?

And should it be a `TimeSpan` argument?

**Comment by HofmeisterAn** [comment]
The [docs](https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerCreate) says:

> Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.

> And should it be a TimeSpan argument?

No, it's a `long`.
